name: Node.js CI

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  # This job will run linting, typechecking and tests on your codebase
  testCodebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      # Install packages
      - run: npm ci

      # Generate prisma client & push to db
      - run: echo "DATABASE_URL=file:./db.sqlite" > .env
      - run: npx prisma db push
      - run: npx prisma generate

      # Run linting and typechecking
      - run: npm run lint
      - run: npm run typecheck

      # Run tests
      - run: npm run test

  # This job will run the app and then use `curl` to visit the index-page. This is a smoke detector check that ensures that your app still builds & runs correctly
  testAppBuildsAndStarts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      # Install packages
      - run: npm ci

      # Generate prisma client & push to db
      - run: echo "DATABASE_URL=file:./db.sqlite" > .env
      - run: npx prisma db push
      - run: npx prisma generate

      # start app in dev mode and load `/`-index page
      - run: "(timeout 60 npm run dev & (sleep 10 && curl --fail localhost:3000)) && echo Run development check successful"

      # build & start app in production mode and load `/`-index page
      - run: "npm run build && (timeout 60 npm run preview & (sleep 10 && curl --fail localhost:3000)) && echo Run production check successful"
  # this publishes a release
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write # publish github release
      issues: write # comment on issues
      pull-requests: write # comment on released pull requests
      id-token: write # enable OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
      - name: Install dependencies
        run: npm ci
      - name: Verify integrity of provenance attestations and registry signatures
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
